export const ProductActionTypes = {
    PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_FAIL: 'PRODUCT_LIST_FAIL'
}

export const ProductDetailsActionTypes = {
    PRODUCT_DETAILS_REQUEST: 'PRODUCT_DETAILS_REQUEST',
    PRODUCT_DETAILS_SUCCESS: 'PRODUCT_DETAILS_SUCCESS',
    PRODUCT_DETAILS_FAIL: 'PRODUCT_DETAILS_FAIL'
}

export const ProductDeleteActionTypes = {
    PRODUCT_DELETE_REQUEST: 'PRODUCT_DELETE_REQUEST',
    PRODUCT_DELETE_SUCCESS: 'PRODUCT_DELETE_SUCCESS',
    PRODUCT_DELETE_FAIL: 'PRODUCT_DELETE_FAIL'
}

export const ProductCreateActionTypes = {
    PRODUCT_CREATE_REQUEST: 'PRODUCT_CREATE_REQUEST',
    PRODUCT_CREATE_SUCCESS: 'PRODUCT_CREATE_SUCCESS',
    PRODUCT_CREATE_RESET: 'PRODUCT_CREATE_RESET',
    PRODUCT_CREATE_FAIL: 'PRODUCT_CREATE_FAIL'
}

export const ProductUpdateActionTypes = {
    PRODUCT_UPDATE_REQUEST: 'PRODUCT_UPDATE_REQUEST',
    PRODUCT_UPDATE_SUCCESS: 'PRODUCT_UPDATE_SUCCESS',
    PRODUCT_UPDATE_RESET: 'PRODUCT_UPDATE_RESET',
    PRODUCT_UPDATE_FAIL: 'PRODUCT_UPDATE_FAIL'
}