export const userActionTypes = {
    userLogin: {
        USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
        USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
        USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
        USER_LOGOUT: 'USER_LOGOUT'
    },
    userRegister: {
        USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
        USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
        USER_REGISTER_FAIL: 'USER_REGISTER_FAIL'
    },
    userDetails: {
        USER_DETAILS_REQUEST: 'USER_DETAILS_REQUEST',
        USER_DETAILS_SUCCESS: 'USER_DETAILS_SUCCESS',
        USER_DETAILS_FAIL: 'USER_DETAILS_FAIL'
    }
}